index:
    pattern: /
    defaults:
        _controller: "Controller:index"
        
hello_world:
    pattern: hello-{nom}
    requirements:
        nom: "[a-zA-Z]+"
    defaults:
        _view: hello
        nom: world
